version: 2.1

orbs:
  android: circleci/android@3.1.0

jobs:
  run-unit-test:
    executor:
      name: android/android_machine
      tag: default
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-{{ checksum "build.gradle.kts" }} - {{ checksum "app/build.gradle.kts" }}
            - gradle-
      - run:
          name: Change permission for gradlew
          command: chmod +x gradlew
      - run:
          name: Resolve all the dependencies
          command: ./gradlew dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle.kts" }} - {{ checksum "app/build.gradle.kts" }}
      - run:
          name: Run Unit Test
          command: ./gradlew testDebugUnitTest

workflows:
  run-unit-test:
    jobs:
      - run-unit-test